name: Deploy React App #имя
on:   # на какое событие будет реагировать этот файл
  push: # пуш на гитхаб
      branches: # фильтрация веток
        - master # на какую именно ветку реагирует workflow
      # paths-ignore: # эти изменения в коде не включают workflow
        # - '.github/workflows/*'
jobs: # работа
  test: #тестируем код
    runs-on: ubuntu-latest # на чем запускаем
    steps: # шаги
      - name: Get repository code # получить код репозитория
        uses: actions/checkout@v3 # использовать готовый workflow
      - name: Cache deps # имя кеш зависимости
        uses: actions/cache@v3 #использовать готовый workflow кеш
        with:
          path: ~/.npm # здесь будет хранится кеш
          key: node-modules-${{ ('**/hashFiles-lock.json') }} # ключ список всех зависимостей
      - name: Install dependecies # имя установить зависимости
        run: npm ci # установить зависимости
      - name: Test application # имя протестировать приложение
        run: npm run test # начать тест
  lint: # проверяем приложение на качество кода
    runs-on: ubuntu-latest # на чем запускаем
    #needs: test # дожидаемся конца test чтобы начать lint
    steps: # шаги
      - name: Get repository code # получить код репозитория
        uses: actions/checkout@v3 # использовать готовый workflow
      - name: Cache deps # имя кеш зависимости
        uses: actions/cache@v3 #использовать готовый workflow кеш
        with:
          path: ~/.npm # здесь будет хранится кеш
          key: node-modules-${{ ('**/hashFiles-lock.json') }} # ключ список всех зависимостей
      - name: Install dependencies # имя установить зависимости
        run: npm ci # установить зависимости
      - name: Lint application # имя проверять приложение на качество кода
        run: npm run lint # начать тест
  build: # собираем приложение
    needs : [lint,test] # дожидаемся конца lint и test чтобы начать build
    continue-on-error: true #продолжить в случае если проект не запусится на какой либо из версий os
    strategy: # стратегия нужна для того ,чтобы протестировать проект на разных опирационных системах
      matrix: # матрица
        node-version: [14,16] # тестируем билд проекта на 14 и 16 node
        os : [ubuntu-latest, windows-latest] # опирационные системы
    runs-on: ${{ matrix.os }} # на чем запускаем (прогоняем и ubuntu и windows)
    steps: # шаги
      - name: Get repository code # получить код репозитория
        uses: actions/checkout@v3 # использовать готовый workflow
      - name: Install Node JS # имя скачиваем NodeJS
        uses: actions/setup-node@v3 # использовать готовый workflow
        with:
          node-version: ${{ matrix.node-version }} # используем и 14 и 16 версию node
      - name: Cache deps # имя кеш зависимости
        uses: actions/cache@v3 #использовать готовый workflow кеш
        with:
          path: ~/.npm # здесь будет хранится кеш
          key: node-modules-${{ ('**/hashFiles-lock.json') }} # ключ список всех зависимостей
      - name: Install dependecies # имя установить зависимости
        run: npm ci # установить зависимости
      - name: Build application # имя собираем приложение
        run: npm run build # собираем приложение
      - name: Deploy # развернуть
        run: echo Deploying ...
