name: Print Pull Request Context  # имя
on:                     #[workflow_dispatch, pull_request] # на какое событие будет реагировать этот файл
    workflow_dispatch: # запускаем вручную через github
    pull_request: # слияние веток в гитхаб
      types: [opened, edited , reopened] # типы (открыть, редактировать, вновь открыть) реагирует pull request
jobs: # работа
  print: # название задачи
    runs-on: ubuntu-latest # на чем запускаем
    steps: # шаги
      - name: Print context # имя контекст печати
        run: echo "${{ toJSON(github.event) }}" # добавляет объект контекста,который позволяет им пользоваться внутри workflow